spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lab2_calc
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 8080
